apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01_namespace.yaml
  - argocd-rolebinding.yaml
  - service-llm-playground.yaml
  - service-llm-pol-mon.yaml
  - podmonitor.yaml
  - pipeline-llm-playground.yaml
  - pipeline-llm-pol-mon.yaml
  - deployment-llm-playground.yaml
  - deployment-llm-pol-mon.yaml
  - route-llm-playground.yaml
  - rbac-llm-pol-mon.yaml
